### ISSUE TITLE
Custom mapping not openning in current release

### ISSUE THREAD

**Issue by CNickDJ** [pestrela/cmdr#10]
Hi, I cant open this mapping in the new release, I've tried exporting per deck, but still getting the same issue.

I've uploaded the mapping.
Thank you so much for your efforts, if I ever make any money from my mappings or when I am more financially stable, I will donate as much as possible. This project has saved me hundreds of hours in time and I appreciate the amount of work that must of gone into making this for free. Thanks again!

the link for the mapping is [here](http://cnick.live/downloads/dj202.zip)

**Comment by pestrela** [comment]
please check your link

I get this:
404
Oops! Page was not found
Sorry, something went wrong and we cannot retrieve the page you were

**Comment by CNickDJ** [comment]
sorry! http://cnick.live/downloads/DJ202.zip

**Comment by pestrela** [comment]
this opens fine with 0.10.3.

download link:
https://github.com/pestrela/cmdr/releases/latest/download/cmdr_tsi_editor_latest.zip

![image](https://user-images.githubusercontent.com/33008932/81577455-59924f80-93a1-11ea-9f9c-c726b74c97ef.png)

**Comment by CNickDJ** [comment]
thankyou, sorry i missed the newest release, sorry for your troubles, thanks a million!
