### ISSUE TITLE
Missing Binary?

### ISSUE THREAD

**Issue by Seriousness** [pestrela/cmdr#2]
Is there any windows build I can use out of the box? If not, could you provide a building manual? Would appreciate it!

**Comment by pestrela** [comment]
binaries:
https://github.com/pestrela/cmdr/releases
https://github.com/pestrela/cmdr/releases/download/0.10.0/cmdr.v0.10.0.zip

compilation steps:
https://github.com/pestrela/cmdr/blob/master/docs/development/Development_Info.md

**Comment by Seriousness** [comment]
Overlooked! Bless & Thanks!
