### ISSUE TITLE
Enhancement idea - INC command

### ISSUE THREAD

**Issue by kaloprojects** [pestrela/cmdr#4]
First of all. HUGE compliment, i just got the link to your project .. and already love it :) .. the NI editor i so terrible, no copy&paste .. cmdr offers this, so amazing THANK YOU ! .. btw: the filtering row on top of columns are best :)

just an enhancement idea .. any kind of INC Command would be nice, see this example: i mapped a lot OUT (LED) actions to e.g. 'Hotcue 1 type' (for each cue type -1 to 5 etc.. for triggering different colors, delete etc), now wanted to copy this dozen of mappings 8x for HC2-8, so i would need a way to update command itself (from 'Hotcue 1 type' to 2, to 3 etc) .. just as an idea ;) 

Anyhow .. GREAT WORK :) ! 

(Just wanted to send a screenshot from example above, but seems not possible in github)

**Comment by pestrela** [comment]
thanks for you kind words.
I have the feature you are describing already done for modifiers (menu modifiers / inc command). Please try it. 

When I work on this gain I will extend this feature to "HC type" as well

What would be useful is if you could provide a full list of all IN+OUT commands that could be rotated (like I have done for modifiers)

PS: screenshots are possible, please see https://github.com/pestrela/cmdr/issues/3

**Comment by kaloprojects** [comment]
Hi ;) .. I was thinking around the last days. Not sure it is possible, but I would recommend a different approach. Do not add additional rotating ideas.. it could be MUCH more efficient if you would do this: Everytime you select several items .. then allow on right panel to edit the 'common' fields. So I could e.g. edit in 'Settings' enter a value for all of them. Currently the setting fields disapper. And ADD the combobox 'command' on rigth panel settings. This would be amazing powerful, would love it and push your tool t a new level. ! :).. and no longer need to add any automatic +/- etc. Do you know what I mean ? (e.g. the mp3 editor mp3tag uses this 'edit multiple rows' idea). mabe too difficult ?

this would e.g. also solve the original idea (to modify hotcuetype 1 to 2): Copy the X hotcue1 rows .. and then i mark them all .. and modify 'command' in right panel to Hotcue 2 type :)

**Comment by pestrela** [comment]
I know what you mean. Would be great.
But rotating commands was easier to code than doing what you suggest. 

I will try again when I return to mappings.

Note that this will take time; my focus is now BOME, reasons below:
https://github.com/pestrela/music/tree/master/traktor#BOME-mappings-migration

**Comment by kaloprojects** [comment]
GREAT .. and yes I know this would mean lot effort (can imagine), but would be a banger :) .. so take your time, good luck (I will still use at it is .. exited the future). Great editor already, well done ! c.u.

.. in once heard about BOME (but never looked in detail).. will check your links, THX ! :)

**Comment by pestrela** [comment]
for clarity I will always use CMDR; 

its just that the complex logic and sate machines (= traktor modifiers) were already moved to BOME in my mappings.  
This in turn simplifies the TSI changes a lot.

**Comment by pestrela** [comment]
Latest version does this
If you find more inconsistencies please reopen the ticket
