### ISSUE TITLE
INC/DEC Value not working in all ENUMs

### ISSUE THREAD

**Issue by ymmer** [pestrela/cmdr#7]
Hi Pedro, 
first of all, thanks for keeping the cmdr up and running. this is a minor issue.

was just playing around with the INC/DEC Command and Value actions and i love that stuff already. felt this was missing since the days around 0.5b ;) the INC/DEC do not seem not to work on all occasions.

![cmdr_2020-04-25_14-58-13](https://user-images.githubusercontent.com/9976444/80280794-aff76100-8706-11ea-83af-a98ece59cc36.png)

expected behaviour was that the INC Value action would increase the command´s value to Hotcue2, but it just does nothing. am i misunderstanding the purpose of that action?

**Comment by pestrela** [comment]
thanks
please report all inconsistencies you find, and I will fix them all

**Comment by pestrela** [comment]
I now added this in 0.10.2
both commands and conditions
https://github.com/pestrela/cmdr/releases/tag/0.10.2
